server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:h2:mem:mydb
    username: bb
    password: test
    driverClassName: org.h2.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true